### PR TITLE
Add a mixin for Bootstrap v5

### PR DESCRIPTION
**Pull request by jeromelebleu**
There are some changes between v4 and v5 which requires a new mixin to render forms with a Bootstrap v5 compatible CSS classes. This first renames `BootstrapTapeformMixin` to `Bootstrap4TapeformMixin` but still provides an alias for backward compatibility, I let you see if it should be removed at some time - I just added a note about the fact that it could happened. Then, a new `Bootstrap5TapeformMixin` is added which inherit from `Bootstrap4TapeformMixin`. As of now, it supports the same fields than `Bootstrap4TapeformMixin` but more could come - i.e. color picker.

The only change is that `small` CSS class is removed from the help text to comply with Bootstrap v5. As we already don't follow the specifications for Bootstrap v4 - see the [doc](https://getbootstrap.com/docs/4.6/components/forms/#help-text), `text-muted` should be added and `<small>` should be used - I guess this should already be tweaked?

This is open for reviews!

### CODE REVIEW

**Comment by jeromelebleu** [comment]
Only `TestBootstrap5TapeformMixin.test_form_field_render[select_multiple]` fails on Django 2.0 due to another formatting of `multiple` attribue. Could Django 2.0 be dropped instead of trying to change this test - which will probably make it complex?

**Comment by stephrdev** [comment]
I think we can drop support for Django < 2.2

**Comment by stephrdev** [comment]
Overall I really like your work on adding support for Bootstrap 5. Thank you very much. I'd be more than happy to get this merged as soon as the Django versions < 2.2 got removed from tox/ci and we have a few words on this in the changelog. I think we will make a major release as we deprecate the Bootstrap mixin - even if you keep a fallback.

**Comment by jeromelebleu** [comment]
You're welcome! Glad to know that we share the same view. I can add a note in the changelog before merging this PR - and after merging the others!

**Comment by stephrdev** [comment]
I just merged the PR that drops 2.0 and 2.1. after rebaseing this PR it should be ready for merge.

**Comment by jeromelebleu** [comment]
> I just merged the PR that drops 2.0 and 2.1. after rebaseing this PR it should be ready for merge.

Thanks! Could you just merge #20 before if it is okay for you please?

**Comment by jeromelebleu** [comment]
> I'd be more than happy to get this merged as soon as the Django versions < 2.2 got removed from tox/ci and we have a few words on this in the changelog.

This was in fact already announced in the changelog of v1.0.0!

**Comment by jeromelebleu** [comment]
Hi @stephrdev, is there any required changes or do you just didn't have the time to have a look? Thanks in advance!

**Comment by stephrdev** [comment]
Sorry, totally missed that one.

**Comment by stephrdev** [comment]
Yes, on Monday when I'm back at the computer :)

**Comment by stephrdev** [comment]
Release 1.1.0 is published.

**Comment by jeromelebleu** [comment]
Wonderful, thanks!

**Pull request merged**
